# Generated by Django 2.1 on 2019-01-30 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 11, 48, 55, 706616, tzinfo=utc)),
        ),
    ]
