# Generated by Django 2.1 on 2019-01-30 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20190130_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='birthdate',
            field=models.DateField(verbose_name='Birhday'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 11, 50, 7, 519709, tzinfo=utc)),
        ),
    ]
