# Generated by Django 2.1 on 2019-01-30 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20190130_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 11, 51, 45, 194262, tzinfo=utc)),
        ),
    ]
