# Generated by Django 2.1 on 2019-01-30 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20190130_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 30, 11, 52, 54, 732101, tzinfo=utc)),
        ),
    ]
